// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
    appId: '1:113562062731:web:99d46884702defb20b298e',
    messagingSenderId: '113562062731',
    projectId: 'todo-list-fd3a0',
    authDomain: 'todo-list-fd3a0.firebaseapp.com',
    storageBucket: 'todo-list-fd3a0.firebasestorage.app',
    measurementId: 'G-1QGHNZYTBZ',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:113562062731:android:6048e8020a59316c0b298e',
    messagingSenderId: '113562062731',
    projectId: 'todo-list-fd3a0',
    storageBucket: 'todo-list-fd3a0.firebasestorage.app',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY'] ?? '',
    appId: '1:113562062731:web:9b8bbd27ff92d45e0b298e',
    messagingSenderId: '113562062731',
    projectId: 'todo-list-fd3a0',
    authDomain: 'todo-list-fd3a0.firebaseapp.com',
    storageBucket: 'todo-list-fd3a0.firebasestorage.app',
    measurementId: 'G-GP84L8QSLV',
  );
}
